### ISSUE TITLE
Adding Searching Algorithm code in C++ 

### ISSUE THREAD

**Issue by shivanithorve01** [CMPN-CODECELL/Hacktoberfest2021#148]
Hello, Shivani Thorve this side. I want to contribute to your repo. Could you please assign this issue to me ?

**Comment by yashrajdesai** [comment]
Which search algorithm are you planning to add?

**Comment by YashMali597** [comment]
Hello , Yash here , I want to contribute to your repo too. Please assign me this task

**Comment by YashMali597** [comment]
I also have some other projects like CNN based Handwritten digit recognition , Chatbot in python without deep learning. Also I can contribute Singly linked list insertion . Please tell me what will be best for this repo that can be accepted from this above mentioned things.

**Comment by yashrajdesai** [comment]
@YashMali597 All the above projects are good to go. ✌ Please open separate issues for the tasks which you are interested to work upon and we'll assign them to you.

**Comment by yashrajdesai** [comment]
@shivanithorve01 You can do the linear search as the binary search algorithm is already merged.
