### ISSUE TITLE
Adding a program implementing bubble sort in C++

### ISSUE THREAD

**Issue by yashviiii** [CMPN-CODECELL/Hacktoberfest2021#36]
adding a code implementing bubble sort using an array in the sorting folder of C++ that takes input from the user and arranges it in ascending or descending order depending on the users requirement.

**Comment by Vishesh-Mittal** [comment]
Sure,go ahead

**Comment by shivani0126** [comment]
I want to contribute in this program of implementing Bubble Sort in C++ please assign this issue to me.

**Comment by Vishesh-Mittal** [comment]
shivani0126 you can work on selection sort or merge and quick sort,just raise a new issue i will assign it to you

**Comment by yashviiii** [comment]
hi i have added the code as required by issue no #36.
