### ISSUE TITLE
Prims Algorithm is Missing

### ISSUE THREAD

**Issue by Akash82228** [CMPN-CODECELL/Hacktoberfest2021#41]
Prim algorithm is missing in C++ language algorithm section. i know algorithms in cpp please assign this issue to me i can add required file.

**Comment by yashrajdesai** [comment]
We have purposefully kept it empty so that contributors can add algorithms in the respective folder. So it's not missing 😉

**Comment by Akash82228** [comment]
yes i know i just have to create issue so that i can pull request. i need to type what's the issue so that you can assign me🏆

**Comment by yashrajdesai** [comment]
Exactly, just saying that it's fine even if you write "Add Prims Algorithm" as word "missing" somewhat changes the context. 🙂

**Comment by Akash82228** [comment]
okay i will take care🙃
