### ISSUE TITLE
Add a Deep Learning project on CNN model using CIFAR Dataset and tensorflow library

### ISSUE THREAD

**Issue by ManthanShettigar** [CMPN-CODECELL/Hacktoberfest2021#43]
To-do list : 

- [x] Load CIFAR dataset
- [x] Explore data
- [x] Data Preprocessing
- [x] Build and train model
- [x] plot losses and accuracy 
- [x] plot confusion matrix 
- [x] show some predictions

Please assign me to work on this issue

**Comment by yashrajdesai** [comment]
Sure 👍

**Comment by yashrajdesai** [comment]
It would be very helpful for us if you can create a separate Machine Learning folder and add your project there.🙌

**Comment by ManthanShettigar** [comment]
Yes , working on it .
