### ISSUE TITLE
DFS(Depth-First-Search) traversal Algorithms in Python

### ISSUE THREAD

**Issue by dhananjaypai08** [CMPN-CODECELL/Hacktoberfest2021#8]
Thinking of working on Algorithms specifically on **DFS** traversal for Binary trees which  includes **Postorder, Preorder, Inorder** traversals. Will be following the contributing guidelines, can you please assign it to me?

**Comment by Akash82228** [comment]
I am good in algorithms i know the BFS and DFS in binary trees very well please can you assign this issue to me i will definitely be able to add these required things in the main code.

**Comment by yashrajdesai** [comment]
@Akash82228 as BFS and DFS is already implemented in trees by @dhananjaypai08 , you can implement it in graphs. Also, you can have a look at other algorithms mentioned in the Algorithms folder or add your own algorithms by first creating a separate issue for it.

**Comment by Akash82228** [comment]
sure @yashrajdesai
