### ISSUE TITLE
Adding code for linear search in Java

### ISSUE THREAD

**Issue by aditib26** [CMPN-CODECELL/Hacktoberfest2021#95]
Hi i want to add the code for linear search in Java which will input the array and element to be searched from the user and display if the element was found or not and at what index. Please assign me the same

**Comment by yashrajdesai** [comment]
Assigned.

**Comment by janhavikale06** [comment]
Hello , I'm Janhavi Kale. I would like to work on this issue , can you please assign me ?

**Comment by yashrajdesai** [comment]
@aditib26 are you still working on it?

**Comment by yashrajdesai** [comment]
@aditib26 what issues are you facing? You can refer to https://github.com/CMPN-CODECELL/Hacktoberfest2021/blob/main/CONTRIBUTING.md

**Comment by aditib26** [comment]
> @aditib26 what issues are you facing? You can refer to https://github.com/CMPN-CODECELL/Hacktoberfest2021/blob/main/CONTRIBUTING.md

I will try creating a pull request again. Thanks

**Comment by janhavikale06** [comment]
What do I do? Can I also work on this?

**Comment by yashrajdesai** [comment]
@janhavikale06 you can open a separate issue on a different algorithm that you would like to work on.
